### ISSUE TITLE
otter-assign should warn when either too many or too few modules are specified in requirements

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#139]
**Is your feature request related to a problem? Please describe.**
After using otter-assign for about six weeks, the need to explicitly list the names of certain python modules in a requirements.txt file has emerged as one of the most frustrating sources of hard-to-track bugs, and as a time-intensive step in the workflow. 

To avoid bugs, every time one adds an "import" statement to a notebook, one must remember to check the relevant library against three lists: 
1) the list of standard python libraries at https://docs.python.org/3/py-modindex.html; this list may change from python version to python version
2) the list of modules in the default requirements at https://otter-grader.readthedocs.io/en/latest/otter_generate/container_image.html#requirements-txt; this list may change from otter version to otter version;
3) a file requirements.txt that must be passed to otter-assign as an argument; this list typically changes from notebook to notebook.

For a given combination of python, otter, and notebook, if the library occurs neither in 1) nor in 2) it must occur in 3). If the library occurs either in 1) or in 2) or both, it must not occur in 3). Thus list 3) must neither contain too many or too few modules.

Otter-assign will not complain about deviations from this rule, but will produce an autograder that silently fails while grading, with no straightforward indication of the problem.

**Describe the solution you'd like**
Otter-assign should prominently warn about deviations from this rule in a preprocessing step, should repeat the warning at the end of its run, and should not produce an autograder. 

**Describe alternatives you've considered**
An alternative would be for otter-assign to figure out the contents of list 3) automatically.

**Additional context**
The TAs and I have lost hours to this bug and have had to bother Chris several times to help us track it down.

**Comment by jkuruzovich** [comment]
I had a similar issue.  I think the issue (and a wide variety of other issues) could be addressed via a `run` or `debug` mode for the container that worked similar to the Docker stacks project(https://github.com/jupyter/docker-stacks).  The problem was not being able to see how the code is running on the container.  For example, if I'm grading locally with a container `otter-grader:latest`, then I should be able to launch an interactive jupyter environment so that I can run the code live and see what happens. Maybe through something like `otter debug --image otter-grader:latest`.  This would launch a jupyter environment on the container. Do you think this would meet the issues you were having trouble with?

**Comment by champoll** [comment]
I'm not using docker, only otter assign and gradescope, so I'm afraid this would not work. I think the issue I described should be caught as early as within otter assign. A run or debug mode for the container seems useful for other purposes though

**Comment by champoll** [comment]
BTW, this package https://github.com/jackmaney/python-stdlib-list "includes lists of all of the standard libraries for Python 2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, and 3.9 along with the code for scraping the official Python docs to get said lists". So it would be easy to determine list 1) depending on the python version. List 2) is internal to otter.
