### ISSUE TITLE
shortening Docker image build times?

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#171]
**Describe the solution you'd like**
Is there any way build times can be shortened for programming assignments on Gradescope? Maybe this can be accomplished by reducing the number of default dependencies, or perhaps we can petition Gradescope to include more complete [base images](https://gradescope-autograders.readthedocs.io/en/latest/manual_docker/). 

I also see `R` stuff going on in this Python assignment build output. Perhaps we can cut that out? This might have to do with issue #170

**Comment by chrispyles** [comment]
Currently there isn't much that we can do on Otter's end for shortening this. It's mostly up to the things that Gradescope includes in the base image and how long it takes to install all of the technologies needed by Otter.

The R stuff occurs because we use one image for all of Otter and conda manages the Python and R installs. It's currently not our intent to separate out Python and R autograding.

**Comment by chrispyles** [comment]
On further consideration, I think that a lot of the R stuff can be removed for pure-Python assignments. I've opened #172 that includes changes to the template structure to separate templates for R and Python assignments.
