### ISSUE TITLE
Can't run "otter assign" on example assignment 

### ISSUE THREAD

**Issue by tanhakabir** [ucbds-infra/otter-grader#221]
**Describe the bug**
Not able to run `otter assign` on example assignment. 

**To Reproduce**
1. Go to [otter-grader.readthedocs.io/en/beta/tutorial](https://otter-grader.readthedocs.io/en/beta/tutorial.html)
2. Download the sample tutorial
3. Run `otter assign assign-demo.ipynb dist`
4. See error:
```
Generating views...
Traceback (most recent call last):
  File "/Users/tanha/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(run_otter())
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/runner.py", line 56, in run_otter
    args.func(**kwargs)
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/__init__.py", line 68, in main
    output_nb_path = write_output_directories(master, result, assignment)
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/output.py", line 147, in write_output_directories
    write_autograder_dir(master_nb_path, output_nb_path, assignment)
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/output.py", line 43, in write_autograder_dir
    transformed_nb, test_files = transform_notebook(nb, assignment)
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/notebook_transformer.py", line 34, in transform_notebook
    transformed_cells, test_files = get_transformed_cells(nb['cells'], assignment)
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/notebook_transformer.py", line 160, in get_transformed_cells
    assignment.update(read_assignment_metadata(cell))
  File "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/otter/assign/assignment.py", line 90, in update
    raise ValueError(f"Unexpected assignment config: '{k}'")
ValueError: Unexpected assignment config: 'instructions'
```

**Expected behavior**
Written files to `dist` folder.

**Versions**
Python: 3.9.1
Otter: 2.1.3

**Additional context**

**Comment by chrispyles** [comment]
The beta docs are currently out of date since we have a stable release. Please see the latest documentation at https://otter-grader.readthedocs.io/en/latest for an up-to-date tutorial.

**Comment by jonluntzel** [comment]
I am dealing with the same error. Referencing the current docs - the tutorial uses "otter assign demo.ipynb dist" to assign. How should we do it?

**Comment by chrispyles** [comment]
I'm not sure what you mean @jonluntzel? The error referenced here was because the tutorial being used was outdated. Are you running the latest tutorial?

**Comment by jonluntzel** [comment]
Yep, I am running the latest tutorial, specifically under the tutorial section of the link you provided. I'll try a couple more things to fix it

**Comment by jonluntzel** [comment]
The current tutorial's zip file provided has a different directory structure than the doc's diagram, it looks like this:

![Screenshot (49)](https://user-images.githubusercontent.com/34121312/108606376-a498b480-736e-11eb-9798-a29a120f47cf.png)

I tried messing around with it and could not get the grading step working, running into either of these errors:

(1) docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/1e561e687618bbeab21270a3f61ca9a6559ab5ffcca4403b8fbb6b3f5bdb684f/archive?path=%2Fautograder%2Fsubmission%2Fdemo-fails3Hidden.pdf: Not Found ("Could not find the file /autograder/submission/demo-fails3Hidden.pdf in container 1e561e687618bbeab21270a3f61ca9a6559ab5ffcca4403b8fbb6b3f5bdb684f")

(2) ValueError: No objects to concatenate

Earlier I was able to run the tutorial just fine so maybe I was using the beta docs with the old otter version. Otherwise I am not sure if it had to do with updating otter, if the docs changed between now and then, or if I just missed something trying to do it again today. Again if I should create a new thread let me know.

Also what does the checkpoint file (assign-demo-checkpoint) do? It's in the zip file provided but not in either of the directory structures on the current or beta docs.

**Comment by chrispyles** [comment]
This is an outdated version of the docs. I ran into this error myself and fixed it by clearing my browser cache and refreshing the page, as described in this issue: https://github.com/readthedocs/readthedocs.org/issues/5088#issuecomment-453134385
