### ISSUE TITLE
Remove grader.check() from Notebooks

### ISSUE THREAD

**Issue by hno2** [ucbds-infra/otter-grader#270]
Hey everyone, 

if I want to check assignment completely automatically and not have students use otter at all, can I remove the grader.checks() ? If so how do I configure this.

Thanks in Advance!

**Comment by chrispyles** [comment]
Currently this needs to be done manually. Note however that if your notebook has no `grader.check` calls then your will need to ensure that there are no variable name collisions in the assignment.

It might be a good idea to make this behavior configurable so that e.g. a metadata flag could be used to remove these calls...?

**Comment by chrispyles** [comment]
This feature is implemented in #303 and will be included in Otter v3.0.0.b2.
