### ISSUE TITLE
Make force_save work with retrolab

### ISSUE THREAD

**Issue by davidwagner** [ucbds-infra/otter-grader#448]
**Is your feature request related to a problem? Please describe.**
Right now force_save will only work in Jupyter notebook, not in retrolab.  In particular, when running in Jupyter notebook, `grader.export(force_save=True)` will force-save the notebook before exporting it to a zip file.  However this uses code that is specific to Jupyter notebooks and won't work with Jupyter Lab retrolab.  We're planning to migrate Data 8 and Data 100 to retrolab (I think Data 100 has already migrated), so we'll need to update this code to work with retrolab.

The current code relies on executing `IPython.display.display(IPython.display.Javascript("Jupyter.notebook.save_checkpoint();"))` (see the code for [save_notebook()](https://github.com/ucbds-infra/otter-grader/blob/6a33a7519c8015201989250a1d185d4b03638892/otter/check/utils.py#L18)).  `IPython.display()` is specific to Jupyter notebook and won't work with retrolab.

**Describe the solution you'd like**
We need to find another way to force-save, maybe a small front-end extension that the otter Python code can communicate to, and then code in otter to call it.

Related: https://github.com/ucbds-infra/otter-grader/blob/6a33a7519c8015201989250a1d185d4b03638892/otter/check/utils.py#L18, https://stackoverflow.com/q/66880698/, https://github.com/jupyterlab/jupyterlab/issues/6161

**Comment by jtpio** [comment]
Right this is definitely specific to the classic notebook which exposes `IPython` and `Jupyter` as globals on the page. This doesn't work in JupyterLab / RetroLab.

The proper way would be to develop a JupyterLab extension and use the JupyterLab API (`notebookTracker.currentWidget` to access the current notebook).

Another option would be to use a bridge like [ipylab](https://github.com/jtpio/ipylab) which is essentially similar to exposing `IPython` and `Jupyter` to the kernel, but for JupyterLab. As mentioned in https://github.com/jupyterlab/jupyterlab/issues/6161#issuecomment-922039473. However this still needs a quick pass so it works in RetroLab too: https://github.com/jtpio/ipylab/issues/33

Otherwise if these `IPython` / `Jupyter` hooks are still heavily used in many extensions, maybe RetroLab should provide a shim or compat layer for them, and use the JupyterLab API instead under the hood (like a proxy).

**Comment by jtpio** [comment]
Another probably simpler approach would be to expose the `jupyterapp` main application on `window` with `--expose-app-in-browser`.

I just updated this gist as an example so it can be tested on Binder: https://gist.github.com/jtpio/4a6a34da66b32249e28df718ec30e4d7

You can open the dev tools and execute `window.jupyterapp.commands.execute('docmanager:save')` if you want to try it out:

![image](https://user-images.githubusercontent.com/591645/140725653-65cf8eab-e356-4344-91a7-41b043676f07.png)

**Comment by jtpio** [comment]
More generally this can be used to execute arbitrary commands from the notebook, for example:

https://user-images.githubusercontent.com/591645/140728366-0883cf50-dba6-4542-b686-940116fd12ec.mp4

**Comment by yuvipanda** [comment]
@jtpio ah great! But I'd imagine that flag is perhaps not going to be turned on by default ever, so it would be great to have other options for python to trigger saving current notebook. See my comment in https://github.com/jupyterlab/retrolab/issues/274#issuecomment-963485275

**Comment by chrispyles** [comment]
Opened #476 which implements a version of force-save compatible with JupyterLab and RetroLab. This will be included in v3.3.0.
