### ISSUE TITLE
Export cell fails to generate PDF for student submission when RAM = 500MB, prints misleading error message

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#484]
**Describe the bug**
The attached MWE-ish notebook, with one manually graded and one autograded question, produces an error when it is run on the JupyterHub student site (though not on the JupyterHub instructor site). The error occurs when the export cell is run. The submission does not include a PDF. 
The error message suggests that this may be related to xeCJK or fandol. It suggests running again with no_xecjk set to True or with the --no-xecjk flag. But it doesn't say *what* should be run again, and I don't know how to follow these instructions.

EDIT: On further investigation, this turns out to be a RAM issue. The instructor site has 1000MB RAM and the student site has 500MB RAM. When the RAM for the student site is increased to 1000MB, the issue disappears.   I missed the issue originally because the notebook's RAM gauge did not increase, presumably because Latex is an external process.

**To Reproduce**
Steps to reproduce the behavior: (EDIT: this assumes that the student site has 500MB RAM)
1. On a JupyterHub instructor site, upload the attached notebook and run `otter assign --v1 assignment01.ipynb dist`. 
2. Copy the dist folder into the student site, e.g. via shared folder
3. Log on to the student site, locate the autograder folder within dist, and open the assignment01.ipynb model solution within this folder
4. Run all the cells and see error

**Expected behavior**
No error should occur and the student should be able to generate a PDF. 
(EDIT: If RAM is low, this should be indicated in an informative error message; ideally the error message should not mention xeCJK or fandol as this is misleading) 

**Versions**
Python version: 3.10.2
Otter-Grader version: 3.2.1

Both the instructor and the student site access the same versions via the same conda environment, which is specified in the notebook via ipykernel 

**Additional context**

[assignment01.pdf](https://github.com/ucbds-infra/otter-grader/files/8353089/assignment01.pdf)
[assignment01.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/8353091/assignment01.ipynb.txt)

![image](https://user-images.githubusercontent.com/7155025/160182234-51b7e0c2-08b8-47dc-a6bf-5394bef07c7f.png)

**Comment by chrispyles** [comment]
Sadly there isn't much that can be done about this issue. To my knowledge, it's not possible to detect an OOM issue when running latex via nbconvert. The message about xeCJK or fandol says "If the error above is related to xeCJK or fandol" to indicate that if the error message says something like xeCJK or fandol is not installed (which the pictured message doesn't), you can disable the use of these features with the specified arguments (in this example, you would add `no_xecjk=True` in the `grader.export` call). Determining whether the error message is related to xeCJK or fandol would involve some text parsing which I'm hesitant to do, since the lack of xeCJK was a common error for a while and I don't want to remove this guidance and have it crop up again.
