### ISSUE TITLE
Does otter-grader have any features to make cheating difficult?

### ISSUE THREAD

**Issue by richardcherron** [ucbds-infra/otter-grader#490]
Does otter-grader have any features to make cheating difficult? I give quizzes in Jupyter notebooks and use otter-grader and Gradescope to grade them. Hidden tests make cheating more difficult because students don't know if they're sharing a perfect quiz. Gradescope can check for similarities between notebooks, but this feature typically fails for me. Are there other features I can use to make cheating difficult? Can I give multiple quiz versions or hide metadata in a notebook?

I know eliminating cheating is difficult, so I assign big weights to hard-to-fake skills (e.g., class participation and open-ended projects). Still, I want to use quizzes because students benefit from low-stakes practice and immediate feedback.

**Comment by chrispyles** [comment]
(Sorry for the delayed response.) Currently, Otter doesn't really have any kind of mechanism to detect/prevent cheating since it doesn't really have a way to compare notebooks to one another (as they're siloed purposefully in separate containers). While it might be possible to create a tool that would work for instructors running Otter locally (presupposing there was a good design for such a tool), it wouldn't work on Gradescope as there's no way to get the containers to communicate with one another since they're ephemeral and are run on-demand rather than all at once.

That being said, I was working on a tool a couple of years ago called [jExam](https://github.com/chrispyles/jexam) that was similar to Otter Assign but could be used for generating randomized versions of autogradable assignments (making it possible with enough question versions for each student to get a unique assignment). I stopped working on it since there didn't seem to be much demand for it, but IIRC the implementation is mostly complete (if not finished) and could be forked/used as inspiration if you've got the time/desire to create your own tooling.

Hope this helps. Closing this ticket as I think I've answered the question but if I've left anything out or you have other questions, please feel free to reopen it.
