### ISSUE TITLE
Hidden test displayed as public in student notebook

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#495]
**Describe the bug**
The attached notebook contains a hidden test. When it is compiled and the student runs the resulting notebook, the hidden test is run and its code, which reveals the solution, is displayed to the student.

**To Reproduce**
1. Run "otter assign --v1 assignment01.ipynb dist" on the attached .ipynb. [assignment01_ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/8834463/assignment01_ipynb.zip)
2. Navigate to dist/autograder 
3. Open and run the assignment01.ipynb notebook 
4. Replace correct answer "42" by incorrect answer such as "32"
5. Run the test cell.

**Expected behavior**
The results of the public test should be displayed but not the code for the hidden test.

**Versions**
Python version: 3.8.5
Otter-Grader version: 3.2.1

**Additional context**
This must have been introduced sometime within the upgrades of otter-grader after Sep 2021 -- the notebook is unchanged since last Fall.

**Comment by chrispyles** [comment]
@champoll the tests directory/notebook in dist/autograder contains all tests (both public and hidden) since it is used to generate the autograder.zip file. If you were to input the answers in the notebook in dist/student, you should only see the results of the public tests. (This is not a behavior change -- this has always been the behavior.)

**Comment by champoll** [comment]
oh I see -- thank you! sorry about the confusion
