### ISSUE TITLE
otter grade execution from notebooks generated in 2020

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#509]
I am having a problem grasping what I am blowing here. I run otter grade/run all the time on notebooks that are created using the latest version of otter-grader. But I am helping a Fresno CC use otter-grader to grade notebooks locally; these notebooks were used/generated from Spring 20. I have the autograder.zip from the same Spring 20. A number of CC use gradescope successfully to grade these notebooks. 

Locally, I am unable to execute successfully. I am using the latest 3.3.0 version of otter-grader - wondering if that is the issue? If I execute:
otter run -a autograder.zip path-to-notebook I get this:
          RuntimeError: Malformed test file: does not define the global variable 'OK_FORMAT'
otter grade -p path-to-submissions -a path-to-autograder i get this:
         Exception: Executing 'lab01fcc/lab01.ipynb' in docker container failed! Exit code: 1

I did try to back the otter-grader version to something earlier but ran into other weird problems.

I am wondering how to get into a state that enables me to get these notebooks graded? I am guessing that there is some combination of the otter-grader version I am running with older notebooks as well as possibly using the wrong grader image?

Thanks

**Comment by chrispyles** [comment]
Yes, it is a version mismatch error. You should be able to downgrade your local install of otter-grader (you can see which version you need by looking inside the requirements.txt in the autograder.zip) and if the version supports `otter run` then that should work. in order to use `otter grade`, you'll need to pull the tag of the Docker image corresponding to that version (e.g. `docker pull ucbdsinfra/otter-grader:x.x.x`) and pass that image name to the `--image` flag: `otter grade <args> --image ucbdsinfra/otter-grader:x.x.x`).

**Comment by sean-morris** [comment]
Perfect. I got it working thank you. The only other issue that came up was that the pip version was not locked in and the newer versions of pip do not support the "file:" attribute included in pip dependencies of environment.yaml. Thanks for pushing through this.
