### ISSUE TITLE
Moving from nbgrader to otter-grader: missing features?

### ISSUE THREAD

**Issue by dirkcgrunwald** [ucbds-infra/otter-grader#537]
We have a few different kinds of classes currently using nbgrader. We're contemplating training people to use otter-grader instead to solve these problems:

1. We'd like a more flexible interface (gradescope) for grading free-form questions that can't be auto-graded
2. Given our current setup, people tend to set up their own nbgrader environments and that's an overhead for some faculty, particularly when multiple teaching assistants need to use the same system

When looking at otter-grader, we think the following can't be done:

1. we have classes that use Julia and also Scala. otter-grader says it supports R and Python. How complex is it to add support for other languages?
2. The "locked cell" feature of nbgrader is convenient because it prevents students from e.g. changing a checker function to work for their code. Is there an equivalent method in otter-grader? I.e. some way to indicate that cells that are not part of the student solution should not be able to be changed?
3. Is there something similar to "nbgrader validate"?
4. Lastly, is there any way to automatically carry over the "problems" and "points" into gradescope to avoid faculty making mistakes?

I think by Berkeley DS standards our classes may be small, but they still have 200-400 students and these last two issues are important to avoid mistakes when creating assignments  (and thus getting 200-400 students made at you).

If some of these features are straight forward to implement, it would be useful to know & we could work on PR's for them.

**Comment by chrispyles** [comment]
> we have classes that use Julia and also Scala. otter-grader says it supports R and Python. How complex is it to add support for other languages?

Pretty complex. In order to add support for R, we created a completely new R client package called [`ottr`](https://github.com/ucbds-infra/ottr) to parse test files, run checks, and handle the autograding internals. To add support for other languages, a similar package would need to be created in that language. We would also need to add support for this language to Otter Assign and Otter Generate, and create a Docker image for grading in.

> The "locked cell" feature of nbgrader is convenient because it prevents students from e.g. changing a checker function to work for their code. Is there an equivalent method in otter-grader? I.e. some way to indicate that cells that are not part of the student solution should not be able to be changed?

In the old version of Otter Assign, we had this feature (where we would set `"deletable": false` and `"editable": false` in the metadata of every question cell). Adding it back is currently in our backlog (#431).

> Is there something similar to "nbgrader validate"?

I'm not too familiar with nbgrader, but from a cursory examination of the docs, my impression is that this command runs an assignment against its tests to ensure that everything passes. Assuming my understanding is correct, yes, this validation is done automatically (unless disabled) as part of Otter Assign.

> Lastly, is there any way to automatically carry over the "problems" and "points" into gradescope to avoid faculty making mistakes?

For the autograded portions of assignments, the questions and point values are provided by the autograder (there's no instructor setup required except uploading a configuration zip file). For manually-graded questions, I don't think Gradescope supports this.

Hope this helps! Please let me know if you have any other questions.

**Comment by chrispyles** [comment]
Going to go ahead and close this but if you've got any more questions please feel free to reopen it.
