### ISSUE TITLE
Add progress indicator to `otter assign`

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#589]
**Is your feature request related to a problem? Please describe.**
On long assignments, it can be hard to know whether `otter assign` is stuck or it is just taking a long time to go through all the questions. Getting some feedback on the grader's progress would be nice.

**Describe the solution you'd like**
It would be convenient if `otter assign` printed which question it was executing. A fancier version would be to add a progress meter such as https://tqdm.github.io/. Something like this should work well

```py
from tqdm import tqdm

...

question_ids = # all question ids in the assignment 
question_progress_bar = tqdm(question_ids)
for question_id in question_progress_bar:
     question_progress_bar.set_description(question_id)
    ...
```

**Comment by joelostblom** [comment]
Just noticed the `-v` prints the questions names, great! I think there is still a case for having a progress bar by default, but that is less important now -v works for the basic functionality

**Comment by chrispyles** [comment]
With the recent release of v5, `-v` will no longer print the question names as they're executing because the notebook is being executed in a separate process thanks to nbclient. It may be possible to use [cell hooks](https://nbclient.readthedocs.io/en/latest/client.html#hooks-before-and-after-notebook-or-cell-execution) to recreate this behavior.

w.r.t. using tqdm, I'll have to see if it works well with Otter's internal logging system. The `-v` flag internally is just making logs get printed to the console, so tqdm will need to work will with that for it to get added.

**Comment by chrispyles** [comment]
#689 adds back the logging of questions as they're being executed with `-v`. I don't think `tqdm` is compatible with how otter's logging works, so I'm going to close this after #689 is merged.
