### ISSUE TITLE
Docker grading gives empty PDFs

### ISSUE THREAD

**Issue by nibheis** [ucbds-infra/otter-grader#600]
**Describe the bug**
We are using the latest otter-grader 4.2.1 and doing the grading using 'otter grade' on a remote docker server.
Once the grading is done, we get the grades in ```final_grades.csv``` (fine!) and a directory called ```submission_pdfs``` (as expected).
The problem is, whatever otter pdf-related parameters we try to change (w/ filtering, w/o filtering, etc.), the PDF files in ```submission_pdfs``` are systematically empty.

We tried running with ```--no-kill``` and then inspect the container after the grading occured, and we could not find any logs with PDF related errors.
It seams like the empty PDF files are created by the ```otter/containers.py``` code... and nothing happens during the grading.

**Expected behavior**
Maybe we are wrong, but we expect to get a PDF version of the students' notebooks after the grading in this ```submission_pdfs``` directory. Are we wrong? 

**Versions**
```
Python 3.8.10
Otter 4.2.1
```
Docker image:
```
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest
 => [1/9] FROM docker.io/ucbdsinfra/otter-grader@sha256:a5efef464ce57e4c019a81df10c3f8bd37076c30171bf18c09746727e8009441
```

Please note that the solution PDF is generated correctly at the ```otter assign``` step.

**Comment by chrispyles** [comment]
Can you send the exact `otter` command you're running and your assignment config zip file? Feel free to PM the zip to me in Otter's Slack (link in README) if you don't want it shared publicly.

**Comment by nibheis** [comment]
Hi, thanks for your reply.

For now, we are building a fake/demo assignment for our professors, based on the tutorial - so nothing confidential :-)

Here is the assignment zip file:
[assignment-autograder_2023_01_30T08_44_15_812868.zip](https://github.com/ucbds-infra/otter-grader/files/10533703/assignment-autograder_2023_01_30T08_44_15_812868.zip)

And here is the complete otter grade command:

```
DOCKER_BUILDKIT=1 DOCKER_HOST=ssh://user@ip_address otter grade -a dist/autograder/assignment-autograder_*.zip -v --pdfs --ext ipynb -p dist/submissions --containers 2
```

Let me know if you need more info.

We had a look at the content of the zip file to get a better understanding of the grading process, and then we checked the logs in the container after the grading. Here is what we noticed/figured out - please correct if we are wrong:

- The ```export_cell``` is an option to add a last cell in the notebook for the students to export the notebook - so it's unrelated to PDF generation in the grading container.

- We had a look at ```setup.sh``` - by using a ```ucbdsinfra/otter-grader``` we should have ```texlive```, ```wkhtmltopdf```, ```conda```, etc. already installed in the base image.

- Errors in the container's log about ```otter-env`` (the conda env) that could not be activated, from ```run_autograder```  (but grading works fine, from the received ```final_grades.csv```)

**Comment by chrispyles** [comment]
It looks like this assignment is not configured to generate PDFs. It's a bit confusing how this works (something I'm trying to streamline in v5) but essentially there are two places that need to be configured for PDFs to be generated: in the assignment config, you must set `generate: pdfs: true`. This tells the grader running inside the Docker container that it should create a PDF of the notebook (it has no effect on whether that PDF is copied out of the container). Then, to tell Otter to copy the PDFs out of the container, you add the `--pdfs` flag to `otter grade` (which I see you have done). So the issue you're seeing here is basically because Otter is being told to copy a PDF file out of the container but the container isn't being told to generate that PDF (hence why they're empty).

N.B. Otter disables several methods of `otter.Notebook` (including `Notebook.export`) when it runs in "grading mode" to prevent unneeded functionality that may interfere with grading (such as exporting submissions and writing to Otter's check log file). This is why any changes to `export_cell` will not affect whether a PDF is generated.

**Comment by nibheis** [comment]
Hi @chrispyles,

Thanks for the detailed instructions.

So, I changed the configuration in the assignment. It now looks like:
```
# ASSIGNMENT CONFIG
run_tests: true
generate:
  pdfs: true
init_cell: false
files: ["figs/sketch.png"]
solutions_pdf: true
template_pdf: false
export_cell:
  pdf: true
  filtering: false
```
I updated otter to version 4.3.1, cleaned all files, and I ran the `otter assign` and the `otter grade` (with `--pdfs`) commands - but the PDFs I get from the container are still empty (not blank PDF, they are 0 bytes).

What am I missing ?
