### ISSUE TITLE
Colab with Otter 4

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#630]
**Describe the bug**
I am unable to run otter 4-based notebooks in Colab. I get an error coming from the file check/notebook.py saying the ./tests directory does not exist. 

It appears to be this [line
](https://github.com/ucbds-infra/otter-grader/blob/047f6622c862a1a3e45a110bdab0475568d3866a/otter/check/notebook.py#L68)

**To Reproduce**
1. Open a Otter-4 based notebook like [this one](https://colab.research.google.com/github/data-8/materials-sp22-colab/blob/main/materials/sp22/lab/lab08/lab08.ipynb)
2. Execute the first cell.

**Expected behavior**
It is my understanding that Otter 4 notebooks don't have the ./tests directory. 

**Versions**
Python 3.9
Otter-grader 4.3.1

![image](https://user-images.githubusercontent.com/1514995/231330066-a86b18b4-3a7e-472c-9bbb-0bc4eb3c4bd2.png)

**Comment by chrispyles** [comment]
It looks like the notebook you linked has its tests stored in the notebook metadata. Since the notebook file doesn't exist in the file system on Colab, Otter requires you to have a local tests directory. To set everything up, you should set `runs_on: colab` in the assignment config for otter assign. After you do this, since you're already cloning the repo, you'll need to upgrade the `otter.Notebook` call to set the `run_tests` argument to the correct path to the tests dir.

Another way of doing this would be to use the new [`tests.url_prefix`](https://github.com/ucbds-infra/otter-grader/blob/master/otter/assign/assignment.py#L179) configuration (added for Jupyterlite before file system access was completed), but `otter.Notebook` will still throw this error, so if you'd prefer to use this pattern, please submit a separate FR.

I also noticed that that notebook has a `grader.export` cell. This cell won't work on Colab for the same reason: there's no local copy of the notebook file to save to, so Otter can't export a submission. Even if the notebook is cloned into Colab's file system from GitHub, Colab doesn't know to save the notebook file to the place it was cloned, so the zip file would contain the notebook exactly as it was cloned from github.

**Comment by sean-morris** [comment]
@chrispyles is there any real reason to use Otter 4 in Colab if we are going to generate the tests directory full of test files anyway?  Otter 3 works great in Colab as it is if you mount a Google Drive in the first cell and clone the repository into to it.

**Comment by sean-morris** [comment]
I addressed this issue by re-running otter assign on the original notebooks with the parameters you suggest. Thanks, all good!
