### ISSUE TITLE
Pretty print causes errors when generating tests

### ISSUE THREAD

**Issue by taylorgibson** [ucbds-infra/otter-grader#716]
**Is your feature request related to a problem? Please describe.**

When writing tests in a jupyter notebook, pretty print is turned on by default. When `otter assign` is run to generate the tests, it does not run the code using pretty print. This difference will cause tests to fail where output matching between pretty print and regular print do not match. For example, long lists are shown one element per line in a jupyter notebook when pretty printed, but all on one line without pretty print. Therefore when `otter` creates the test, it doesn't pass on the terminal.

![image](https://github.com/ucbds-infra/otter-grader/assets/5053805/a16861d9-731f-4b5b-9d53-b494a484fa9f)

I'm unsure, would a student pass when completing the assignment since their notebook would also be pretty printed? If so, the error message when running `otter assign` is confusing if everything would actually work as intended.

**Describe the solution you'd like**

Would there be a way to ensure that when creating and running tests, all pretty print is turned off behind the scenes? This should create consistent testing regardless of if the notebook is using pretty print or not, since it becomes standardized upon grading.

**Describe alternatives you've considered**

**Additional context**

**Comment by chrispyles** [comment]
Given that this is a problem that can be alleviated by changing how you write your tests, e.g.

```python
assert my_list == [1, 2, 3]
# or, for more robust tests
assert all(math.isclose(a, b) for a, b in zip(my_list, [1, 2, 3]))
```

Since doctests use string comparisons under the hood, in general it's not a good idea to rely on the `repr` of objects to be consistent when writing tests. This is doubly the case for things like floats, which can be rounded differently depending on the environment. When I author notebooks, I tend to use `assert`s or primitives that have a simple, well-defined `repr` (i.e. ints and booleans).

Given the inherent flakiness of these types of tests, I'm not sure if this is something that Otter should take care of. Instead, I think it would be better to encourage users to write more robust tests. Maybe this is something that can be added to the documentation. (We did write some [autograder test documentation](https://autograder-tests.readthedocs.io/) a few years ago, but that wasn't specific to Otter and doesn't mention this specific point.)

**Comment by taylorgibson** [comment]
I see what you're saying, and you're probably right. One thing I really liked about otter using the output of the cell as one of the values in the string comparison is that it always you to write dynamic tests. For example:

<img width="622" alt="image" src="https://github.com/ucbds-infra/otter-grader/assets/5053805/067f2fda-c690-442a-ba2e-e562f03db99e">

If I were to change the solution values in the array the next time I use this assignment, all I would have to do is change the solution and rerun the notebook. My solution will propagate through the tests, with new outputs generated in each of the test cells, which would then be used to create the tests. As an author, it's a lot easier to just change your solution, and not have to follow that change through all of the tests. Maybe this is bad practice, but it definitely makes reusing assignments (or creating multiple versions of the same assignment) a lot easier. Is there a way to retain this functionality that doesn't rely on string comparisons and their `repr`? I would certainly love guidance on writing robust tests!

**Comment by chrispyles** [comment]
> Is there a way to retain this functionality that doesn't rely on string comparisons and their `repr`?

Not really. There are two ways to write Python tests in Otter: OK format (what you're using, which relies on doctests and therefore `repr`/string comparisons) and the exception-based format (like pytest). The exception-based format doesn't use the output of the cell at all, so you'd still need to hardcode the expected values into the test code.

I think if you call `print` directly it bypasses the default pretty-printing in Jupyter. For handling things like floats, you can use the `hash` function to stably convert the numbers to ints. So something like

```
print(list(hash(e) for e in interesting_numbers))
```

+1 that it's easier to write tests this way, but I don't want to build support for this into Otter directly because there are too many edge cases that would need to be accounted for.
