### ISSUE TITLE
mention gradescope in the username/password prompt of otter assign

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#724]
Hi Chris, would it be possible to mention gradescope in the username/password prompt of otter assign? this was a source of confusion for one of my course assistants who thought it related to the LMS username/password

Thank you!

**Comment by chrispyles** [comment]
@champoll are you referring to the case when you run otter assign without pre-specifying a token or username/password and otter assign asks you to type them in? Because it looks like that prompt already references the fact that it's for Gradescope: https://github.com/ucbds-infra/otter-grader/blob/master/otter/generate/token.py#L37

**Comment by champoll** [comment]
Yes, you’re right , The username prompt mentions gradescope, but for some reason my course assistant was still confused, would you mind adding a reference to gradescope to the password prompt too?
