### ISSUE TITLE
Convert python notebook to a python script file

### ISSUE THREAD

**Issue by KshitijKarnawat** [ucbds-infra/otter-grader#784]
**Is your feature request related to a problem? Please describe.**
While working with Gradescope annotations are not possible for python notebooks. Having a plugin or function that converts the `python notebook (.ipynb file)` into a `python script (.py file)` would be a great help as python scripts can be annotated on Gradescope. As students are not very attentive to instructions many do not submit the secondary python file generated using the current method. (students just submit the zip file generated from otter and forget to submit the python file)

**Describe the solution you'd like**
A function or plugin that can convert `.ipynb` files into `.py` files

**Describe alternatives you've considered**
Write now we have a command line function in the notebook which uses `nbconvert` to convert the files and have students submit 2 different files (the zip file generated using otter and a python file)

**Comment by chrispyles** [comment]
Otter has a plugin system that is easy to extend if you'd like to write your own plugin to accomplish this: https://otter-grader.readthedocs.io/en/latest/plugins/index.html

For your existing solution, you can have otter include the .py file your script generates in its zip file by adding the [`files` argument](https://otter-grader.readthedocs.io/en/latest/otter_check/index.html#otter.check.notebook.Notebook.export) to `Notebook.export` (so that students only need to submit the zip file). If you're using otter assign, this can be set in the assignment config. For example, if your script writes a file named `hw01.py`:

```yaml
# ASSIGNMENT CONFIG
export_cell:
  files:
    - hw01.py
```

If you'd like a built-in method of doing this (i.e. for us to write a plugin that's built into Otter for this), I'm happy to leave this open but I don't know when I'll get around to it.

**Comment by KshitijKarnawat** [comment]
@chrispyles Thanks for the quick reply. 

This indeed resolves most of our issues. 

I will close this issue. I understand that making this a built-in feature is not on your priority list and the workaround is quite good for the issue and easy to set up.

Thanks.
