### ISSUE TITLE
Compatibility with Gradescope Notebook Preview

### ISSUE THREAD

**Issue by shreyanshc** [ucbds-infra/otter-grader#86]
Currently otter-grader output is html formatted, which has problem being displayed in code preview window for the jupyter-notebook. Are there any plans in future to include a fix to main branch? What should be best way to make otter output compatible? Please share your thoughts.

What it looks like right now: 

![image](https://user-images.githubusercontent.com/38718935/83573923-37dc4200-a4e1-11ea-9d91-07673a84542f.png)

How it should look like, which would to helpful for TAs to grade submissions (or figure out problems with their autograder setup):

![image](https://user-images.githubusercontent.com/38718935/83574266-fd26d980-a4e1-11ea-875b-ba1ad73b54b0.png)

Also in Autograder Output tab under results, the HTML object cannot be read with only final scores being displayed properly (same goes for debugging via ssh, autograder outputs show as "<IPython.core.display.HTML object>" )

![image](https://user-images.githubusercontent.com/38718935/83716790-93780e00-a64e-11ea-9aa4-cd2586dae2a0.png)
![image](https://user-images.githubusercontent.com/38718935/83716822-a4c11a80-a64e-11ea-8639-6a07bb44afac.png)

Thank you!

**Comment by chrispyles** [comment]
(Sorry for taking so long to respond to this issue.)

Currently, we don't really have a plan to update this behavior. It might be worthwhile changing how the results are displayed in `Notebook.check_all` (which is doable) but the second issue is not something I'm sure *should* be fixed. This is because in the Gradescope containers the tests that are run contain hidden tests, so these display objects will show the output of failed, potentially hidden tests, which makes the hidden tests un-secure. It is for this reason that the autograder populates the fields below the Autograder Output section with text that shows the output of the failed tests.

One potential idea is to add the "All tests passed" message to the boxes for clarification, which is something I will look into, along with the updated to `Notebook.check_all`.

[ ] Add "All tests passed" messages to GS output
[ ] Update `Notebook.check_all` so that it displays correctly in JN renderer

**Comment by chrispyles** [comment]
#93 addresses the two fixes discussed here. GS's JN renderer now shows this:

<img width="984" alt="Screen Shot 2020-06-21 at 10 10 17 PM" src="https://user-images.githubusercontent.com/40970945/85250667-10a3d100-b40c-11ea-9a87-a6073038ffa1.png">

It also includes the additional test passed message for passed tests.

**Comment by chrispyles** [comment]
Closing this issue since (I think) this has been merged into the beta release already.
