### ISSUE TITLE
Cell Specification Feature

### ISSUE THREAD

**Issue by Ophir-Gal** [ucbds-infra/otter-grader#99]
It would be awesome if the beta release of Otter had an option to specify which code cells to include/exclude when executing a student's notebook submission. For example, maybe the first few cells of the submission are code examples that are irrelevant to the testing of the student's submission.

**Comment by chrispyles** [comment]
OK how is it to instead of flag specific cells _for_ execution, we instead tag cells that _shouldn't_ be executed. It's a pretty simple fix and basically what I'm thinking is that all cells that shouldn't be executed are tagged with `otter_ignore` and then they'll get filtered out before the notebook is executed. I think this solution makes more sense so that it's backwards compatible w/ current behavior (otherwise all notebooks would need to be edited to include those tags to indicate execution).

**Comment by Ophir-Gal** [comment]
Yeah, sounds reasonable. Offering both ways just offers more flexibility (cause one could also have only a few cells they wanna execute..), but backward compatibility is important too 👍

**Comment by chrispyles** [comment]
Closing this issue as this appears to be resolved.
